/**
 * Regenerates src/core/content/source.ts from whatever is in src/content.
 *
 * The bundler needs static imports, and hand-maintaining 40+ of them across
 * two languages is exactly the kind of list that goes stale. Run this after
 * adding or translating a lesson:  npm run sync:content
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const contentDir = path.join(root, 'src/content');
const target = path.join(root, 'src/core/content/source.ts');

const lessonNames = (dir) =>
  fs.existsSync(dir)
    ? fs
        .readdirSync(dir)
        .filter((f) => f.endsWith('.json'))
        .map((f) => path.basename(f, '.json'))
        .sort()
    : [];

const camel = (name, prefix = '') =>
  prefix + name.replace(/[-_](.)/g, (_, c) => c.toUpperCase()).replace(/^./, (c) => (prefix ? c.toUpperCase() : c));

const languages = fs
  .readdirSync(contentDir, { withFileTypes: true })
  .filter((e) => e.isDirectory() && e.name !== 'lessons')
  .map((e) => e.name)
  .sort();

const en = lessonNames(path.join(contentDir, 'lessons'));

const imports = [
  `import subjects from '../../content/subjects.json' with { type: 'json' };`,
  `import modules from '../../content/modules.json' with { type: 'json' };`,
  '',
  ...en.map((name) => `import ${camel(name)} from '../../content/lessons/${name}.json' with { type: 'json' };`),
];

const entries = [`/** Name → raw JSON, so validation errors can say which file is at fault. */`, `const enLessons: Record<string, unknown> = {`];
for (const name of en) entries.push(`  '${name}': ${camel(name)},`);
entries.push('};');

const translationBlocks = [];
for (const language of languages) {
  const dir = path.join(contentDir, language);
  const names = lessonNames(path.join(dir, 'lessons'));
  const hasCatalog = fs.existsSync(path.join(dir, 'catalog.json'));
  if (hasCatalog) {
    imports.push('', `import ${camel(language, '')}Catalog from '../../content/${language}/catalog.json' with { type: 'json' };`);
  }
  for (const name of names) {
    imports.push(`import ${camel(name, language)} from '../../content/${language}/lessons/${name}.json' with { type: 'json' };`);
  }
  const lessonEntries = names.map((name) => `    '${name}': ${camel(name, language)},`).join('\n');
  translationBlocks.push(
    `  ${language}: {\n` +
      (hasCatalog ? `    catalog: ${camel(language, '')}Catalog,\n` : '') +
      `    lessons: {\n${lessonEntries}\n    } as Record<string, unknown>,\n` +
      `  },`,
  );
}

const file = `/**
 * The raw, *unvalidated* content source.
 *
 * GENERATED by \`npm run sync:content\` — do not edit by hand.
 *
 * These imports are the only place in the app that touches content files
 * directly, and everything they hand out is \`unknown\` on purpose: the bundler
 * will happily give us whatever JSON is on disk, and nothing may be trusted
 * until \`validateCatalog\` has run over it.
 */
import type { RawContent } from './validateCatalog.ts';

${imports.join('\n')}

${entries.join('\n')}

export const rawContent: RawContent = {
  subjects,
  modules,
  lessons: enLessons,
  translations: {
${translationBlocks.join('\n')}
  },
};

/** Kept for the content validator, which checks every file on disk is registered. */
export const rawLessons = enLessons;
`;

fs.writeFileSync(target, file);
console.log(
  `source.ts regenerated — ${en.length} English lessons` +
    languages.map((l) => `, ${lessonNames(path.join(contentDir, l, 'lessons')).length} ${l}`).join(''),
);
